### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by gojanpaolo** [deadlydog/VS.DiffAllFiles#21]
Hello, are there any plans to make a VS 2019 compatible version? Thanks! :)

**Comment by deadlydog** [comment]
Yeah, I do plan on updating it to support VS 2019; I just need to actually find the time to do it! I'm totally open to a pull request if somebody else wants to take a whack at it :)

**Comment by gojanpaolo** [comment]
I wanted to do it but I get compile errors. I'll try to take a stab at it again. :)

**Comment by deadlydog** [comment]
This is now released :)

**Comment by gojanpaolo** [comment]
Awesome! Thank you @deadlydog
