### ISSUE TITLE
Wiki Edit

### ISSUE THREAD

**Issue by tigerhawkvok** [deadlydog/VS.DiffAllFiles#31]
On https://github.com/deadlydog/VS.DiffAllFiles/wiki/Common-Diff-Tool-Configurations-For-TFVC ....

The new file name for the native differ is `vsDiffMerge.exe`. 

For Visual Studio 2017, the most common location is `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\vsDiffMerge.exe`.

Took me an hour and a half to find it, though your Wiki was a lot of help along the way.

**Comment by deadlydog** [comment]
Cool, thanks for the info. If you just don't specify an external tool in Visual Studio it should just use that native diff tool, no?

**Comment by deadlydog** [comment]
I've updated the wiki page to include the info. Thanks :)
