### ISSUE TITLE
Using Git, diff all files will open all diffs at once

### ISSUE THREAD

**Issue by mnissl** [deadlydog/VS.DiffAllFiles#38]
When using TFVC, the "All Files" button will diff the first file and only open the diff for the next file when you click on "Next" or close the diff.

When using Git, the "All Files" button will open diffs for all files at once.

**Comment by deadlydog** [comment]
Hmmm, that is supposed to be controlled by this setting.

![image](https://user-images.githubusercontent.com/1187140/69155014-9e01fa00-0aa6-11ea-88b9-fab04a4d3edc.png)

Can you provide screenshots of both your settings window (like above), as well as your Team Explorer window settings for both a Git repo and a TFVC one, like this:

![image](https://user-images.githubusercontent.com/1187140/69155121-c4c03080-0aa6-11ea-928c-92ab54c7c263.png)

Perhaps you have `Combine` checked on one, but not the other, or something like that?

**Comment by mnissl** [comment]
Well I have the same settings:

![grafik](https://user-images.githubusercontent.com/53003618/69173380-f1546680-0aff-11ea-8e40-521d2b314fa5.png)

And Diff All Files looks pretty the same in Team Explorer for Git:

![grafik](https://user-images.githubusercontent.com/53003618/69173453-1943ca00-0b00-11ea-944a-e717b47441ba.png)

... as for TVSC:

![grafik](https://user-images.githubusercontent.com/53003618/69173617-6889fa80-0b00-11ea-9a98-8b7cd7b5e32e.png)

**Comment by deadlydog** [comment]
That is very odd. What program do you have configured as your Git Diff tool? If you change it to a different tool, do you still have the same problem @mnissl ?

**Comment by mnissl** [comment]
I'm using the "Git Extensions" application; its Settings dialog said that the "effective" configuration regarding the difftool was Araxis Merge -- though Visual Studio always uses vsdiffmerge to for diffing files (so does VS.DiffAllFiles). In Git Extensions, I switched from Araxis to vsdiffmerge ... and the problem is gone! Curiously, even if I switch back to Araxis, DiffAllFiles behaves as expected. Strange ...

Thanks for your help! 👍

**Comment by deadlydog** [comment]
That's definitely a curious bug. Thanks for reporting your findings back to this issue! 👍
