### ISSUE TITLE
Error when trying to diff files in git repo

### ISSUE THREAD

**Issue by pprochnau-ipipeline** [deadlydog/VS.DiffAllFiles#52]
We recently switched to git from TFS for our source code manager.  When trying to use Diff All Files on my git repo, I always get an error:
 Unexpected Error Occurred:
StrictFilePathMarshaler must be used on a FilePath.

Currently on VS2019 v16.5.4
DiffAllFiles 1.0.4

**Comment by deadlydog** [comment]
Thanks for reporting this. I'm going to close this issue as it's a duplicate of #14
