### ISSUE TITLE
Extension options/settings are not saved after restarting Visual Studio

### ISSUE THREAD

**Issue by MidniteWatchman** [deadlydog/VS.DiffAllFiles#53]
The How To Compare Files options are not saved.

Steps to reproduce using VS2019 (Professional):
1) In Options->Diff All Files->General, I set How To Compare Files to "Always compare each file independently", with the Maximum number of files to compare at a time to 999.
2) Close VS2019
3) Re-open VS2019
4) In Options->Diff All Files->General, the How To Compare Files has reverted back to the default of "Allow me to decide by showing a checkbox on the UI", and the Maximum number of files to compare at a time is set back to 1.

**Comment by deadlydog** [comment]
Thank you for reporting this. It looks like the `Restore default settings" button is also broken. VS 2019 must've made a breaking change in the way it handles settings from extensions. This will need more investigation. PRs are welcome :)

**Comment by deadlydog** [comment]
This issue should now be fixed in v1.0.5 of the VS 2019 extension. If you still encounter issues saving settings or restoring the default ones, let me know. Thanks!
