### ISSUE TITLE
Settings not saved

### ISSUE THREAD

**Issue by wilsade** [deadlydog/VS.DiffAllFiles#54]
Hi.

General settings not been saved after Visual Studio restart:

1. Open Visual Studio;
2. Go to Tools | Options | Diff All Files | General;
3. Uncheck "Compare deleted files", Check "Always compare each file independently", maximum number 3;
4. Click "OK" to close options;
5. Close Visual Studio;
6. Open Visual Studio;
7. My settings on step 3 are not there!!!

Thanks,

**Comment by deadlydog** [comment]
Thanks for reporting this. It looks to be a duplicate of #53 so I'm going to close this one.
