### ISSUE TITLE
"Unexpected Error Occurred: Attempted to divide by zero."

### ISSUE THREAD

**Issue by srgloureiro** [deadlydog/VS.DiffAllFiles#59]
I frequently get the 
"Unexpected Error Occurred:
Attempted to divide by zero."
message, when I select All files, Included or Excluded. I can diff the 1st file, but no other after it. :(
![image](https://user-images.githubusercontent.com/6369967/119386151-0692ee00-bcbf-11eb-9f08-aedcf215a5de.png)

**Comment by deadlydog** [comment]
Hmmm, I haven't experienced this myself, but thanks for reporting it. I've finally found time to update this extension again, so I'll see if I can track this one down.

**Comment by deadlydog** [comment]
Would you mind posting a screenshot of your current Diff All Files settings as well, like this please:

![image](https://user-images.githubusercontent.com/1187140/119388095-12fb5480-bc87-11eb-870f-e21fca9abc25.png)

**Comment by srgloureiro** [comment]
![image](https://user-images.githubusercontent.com/6369967/119418267-833dc080-bcef-11eb-97cf-33cda00e5771.png)

**Comment by deadlydog** [comment]
Thanks @srgloureiro , I think the problem may be that you have the `Maximum number of files to compare at a time` set to 0, even though it's parent radio button isn't selected. Can you change that value to 1 and see if the problem persists and let me know? I can update the code to ensure that value never goes below one, but you can see if that fixes the issue up for you right now.

**Comment by deadlydog** [comment]
Yeah, I agree the UI is misleading. It's kind of weird because that value is used in 2 of the 3 radio buttons, so it doesn't really belong under a single radio button, but also doesn't quite fit outside of the radio buttons either. At the very least I'll look at limiting that value to be 1 or greater. Thanks for confirming that was the fix 👍

**Comment by deadlydog** [comment]
I've committed a fix that should prevent it from every being set to zero again. It will be available in the next VS 2019 extension version, after v1.0.5. Thanks.
