### ISSUE TITLE
VS 2017 Support

### ISSUE THREAD

**Issue by sheldonhull** [deadlydog/VS.DiffAllFiles#6]
Any plans on updating for VS 2017? If not, I'll have to look further to contribute as this extension has proved very useful in doing larger code comparisons!

**Comment by deadlydog** [comment]
Yup, I have plans to. I started the `AddVs2017Support` branch a while ago, but haven't had time to get back to it yet. You're welcome to pull it down and continue where I left off though. Right now everything compiles, but it gives run-time errors.

**Comment by deadlydog** [comment]
Just an FYI that I have been working on this, but am stuck at an error loading an assembly. Here is the relevant StackOverflow post http://stackoverflow.com/questions/43386787/debugging-visual-studio-2017-extension-does-not-find-assembly

**Comment by deadlydog** [comment]
Finally got it all figured out and merged in with PR #9 :) It's now available in the VS Marketplace.

**Comment by sheldonhull** [comment]
Thank you @deadlydog . I updated my [original blog post](https://www.sheldonhull.com/blog/diff-all-files-reviewing-changesets-quickly?rq=diff%20all%20files) with details on your work. I really appreciate the update of this great tool. Was really missing it!
