### ISSUE TITLE
Getting error while  loading the tool

### ISSUE THREAD

**Issue by gb2017** [deadlydog/VS.DiffAllFiles#7]
Hi,
I am getting the following error when I am trying to compare files. 

![image](https://cloud.githubusercontent.com/assets/24918893/24471441/bf3d5f92-1487-11e7-944d-ab285c90075d.png)

**Comment by deadlydog** [comment]
Hi @gb2017, are you in a Git repository or TFVC source control. My guess is that you do not have your diff tool configured properly. You can refer to [the wiki][WikiUrl] for how to configure your diff tool.

Let me know if that gets you going or not.

[WikiUrl]: https://github.com/deadlydog/VS.DiffAllFiles/wiki

**Comment by deadlydog** [comment]
Hi @gb2017, there has not been any response about this issue, and I suspect the problem was simply a misconfiguration in the .gitconfig file, so I'm closing this one. If you are still having the problem and can provide more information, feel free to reopen this.
